### ISSUE TITLE
Implement new Metastring class

### ISSUE THREAD

**Issue by ingvagabund** [Bihanojko/SpecParser#3]
**TODO**
* [x] move all metaclass relevant code under new `Metastring` class
* [x] extend the `Metastring` class with suitable methods and integrate them into relevant methods/functions in `model_methods.py` and `model_2_methods.py` files
* [x] demonstrate usage of the `Metastring` class in a set of examples
