### ISSUE TITLE
Transform `SpecfileClass('Specfile 2.0')` into its own module

### ISSUE THREAD

**Issue by ingvagabund** [Bihanojko/SpecParser#4]
**TODO**
* [x] implement new `SpecModel` class encompassing current `SpecfileClass('Specfile 2.0')`
* [x] implement new `SpecModelGenerator` class transforming the raw spec file into the new `SpecModel` class
* [x] move and refactor all relevant procedures/functions under `model_methods.py` and `model_2_methods.py` under the `SpecModelGenerator` class

**Story**:
The `SpecModel` is the first product that is consumable outside of the library. One can either transform an instance of the class into a spec file (no transformation to `SpecFileV1`) or queue it for other processing like transformation into `GoSpecModel` class (yet to be implemented). The `SpecModel` provides various manipulation operations such as:
* add/remove subpackage
* add/remove subpackage buildtime/runtime depedency
* edit summary of a subpackage
* add/remove tests to/from %check section
* add/edit/remove macros/tags
* other

**Comment by ingvagabund** [comment]
Partially implemented through https://github.com/Bihanojko/SpecParser/pull/11
